# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ImageWrapping
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
INCLUDEPATH += C:\Qt\Qt5.12.12\Docs\Qt-5.12.12\eigen-3.4.0\eigen-3.4.0
include(ImageWrapping.pri)
